name: Flask App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest  # Runs the job on an Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checks out the repository

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"  # Specifies Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements.txt
        pip install flake8  # Install flake8 for linting
        pip install flask  # Install flask if not already in requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Lint critical issues
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  # General linting

    - name: Run Flask app (sanity check)
      run: |
        python app.py &  # Run Flask app in the background
        sleep 5  # Wait for a few seconds to ensure the app starts
        curl -f http://127.0.0.1:5000 || exit 1  # Send a request to the app to verify it's running

    - name: Run unit tests
      run: |
        python -m unittest discover  # Run all unit tests in the repository

    - name: Clean up (Optional)
      run: |
        kill $(lsof -t -i:5000)  # Kill the Flask app if it's still running (to avoid any conflicts)
